#!/bin/bash

echo "🚀 AgriLink Full Stack Deployment Guide"
echo "========================================"

echo ""
echo "📋 STEP 1: Database Setup"
echo "-------------------------"
echo "Choose your database provider:"
echo "1. Render PostgreSQL (Free tier available)"
echo "2. Supabase PostgreSQL (Free tier available)"
echo "3. Railway PostgreSQL (Free tier available)"
echo ""
echo "After creating your database, copy the DATABASE_URL"

echo ""
echo "📋 STEP 2: Backend Deployment"
echo "-----------------------------"
echo "1. Go to Render.com and create a Web Service"
echo "2. Connect your GitHub repository"
echo "3. Use root directory: apps/backend"
echo "4. Set environment variables:"
echo "   DATABASE_URL=your_postgres_url_here"
echo "   JWT_SECRET=agrilink-super-secret-jwt-key-production-2025"
echo "   IOT_MASTER_KEY=AGRILINK_IOT_MASTER_KEY_2025_PRODUCTION"
echo "   NODE_ENV=production"

echo ""
echo "📋 STEP 3: Frontend Configuration"
echo "--------------------------------"
echo "1. Update apps/frontend/.env.production with your backend URL:"
echo "   VITE_API_URL=https://your-backend-url.onrender.com/api"
echo "2. Rebuild and deploy frontend:"
echo "   npm run build"
echo "   firebase deploy --only hosting"

echo ""
echo "📋 STEP 4: Test the Connection"
echo "-----------------------------"
echo "1. Visit your deployed frontend"
echo "2. Login with demo accounts (password: password123):"
echo "   - farmer@agrilink.local"
echo "   - buyer@agrilink.local" 
echo "   - inspector@agrilink.local"
echo "   - admin@agrilink.local"
echo "3. Test creating lots and placing bids"

echo ""
echo "🎉 Your AgriLink application will be fully connected to a production database!"