services:
  - type: web
    name: agrilink-backend
    rootDir: apps/backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build && pnpm prisma generate
    startCommand: pnpm start
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
